### ISSUE TITLE
mcp query fails when no threshold is specified

### ISSUE THREAD

**Issue by davidor** [ftomassetti/effectivejava#43]
When I execute lein run -- --query mcp the program raises a NullPointerException.
It does not happen if I specify a threshold: lein run -- --query mcp -t 1, but raises the same kind of exception if the threshold is <= 0.

**Comment by ftomassetti** [comment]
ok, found the reason.
It is a bug in JavaParser, currently fixed in the master branch (I think I fixed it :D).
Basically when the number of parameters of a method or a constructor is zero an internal list named parameters is null instead of being an empty list.

I think we can find a workaround for now, and it should be solved in the next release of JavaParser, which should be released quite soon.

**Comment by ftomassetti** [comment]
it should be fixed by 9c82b3fa2de24b105c25698609a5dd36e64218d2

**Comment by ftomassetti** [comment]
I will close, feel free to reopen if you see the issue again
